
repos:
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
      - id: go-fmt-import
      #- id: go-vet
      - id: go-lint
      # - id: go-unit-tests
      - id: gofumpt # requires github.com/mvdan/gofumpt
      # Broken- id: go-err-check # requires github.com/kisielk/errcheck
      - id: go-static-check # install https://staticcheck.io/docs/
      - id: golangci-lint # requires github.com/golangci/golangci-lint
        args: [--config=.github/linters/.golangci.yml] # optional
      - id: go-ruleguard # requires https://github.com/quasilyte/go-ruleguard
        args: [rules/rules.go] # required
  - repo: https://github.com/turo/pre-commit-hooks
    rev: v3.4.1
    hooks:
      - id: gomarkdoc
        args: [-o README.md, --template-file file=config/gomarkdoc/file.gotxt, -e .]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: check-toml
    - id: check-yaml