name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref }}
      GITHUB_ACTOR: ${{ github.actor }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.4

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"

      # Temporarily disable
      # - name: Generate changelog
      #   uses: github-changelog-generator/action@v1.4.4
      #   with:
      #     user_email: "noreply@github.com"
      #     user_name: ${{ env.GITHUB_ACTOR }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     exclude_labels: "wontfix,invalid"
      #     future_release: v${{ env.VERSION }}
      #     output_file: CHANGELOG.md

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
